metadata-version = "2015-12-19"
log-level = "debug"
interval = 30
onetime = false

[[ template ]]
source = "/etc/rancher-conf/plugins.txt.tmpl"
dest = "/etc/rancher-conf/plugins.txt"

[[ template ]]
source = "/etc/rancher-conf/fluent.conf.tmpl"
dest = "/etc/rancher-conf/fluent.conf"
notify-cmd = "/opt/rancher/bin/reload.sh"
notify-out = true
