metadata-version = "2015-12-19"
log-level = "debug"
interval = 30
onetime = false

[[ template ]]
source = "/etc/rancher-conf/plugins.txt.tmpl"
dest = "/etc/rancher-conf/plugins.txt"
check-cmd = "! cmp {{staging}} plugins.installed.txt"

[[ template ]]
source = "/etc/rancher-conf/agent.conf.tmpl"
dest = "/etc/rancher-conf/agent.conf"
notify-cmd = "/opt/rancher/bin/reload.sh"
notify-out = true

[[ template ]]
source = "/etc/rancher-conf/collector.conf.tmpl"
dest = "/etc/rancher-conf/collector.conf"
notify-cmd = "/opt/rancher/bin/reload.sh"
notify-out = true
